/*
 * Copyright (C) 2007 Automation technology laboratory,
 * Helsinki University of Technology
 *
 * Visit automation.tkk.fi for information about the automation
 * technology laboratory.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston,
 * MA 02111-1307, USA.
 */
package wizard;

import static wizard.WizardTools.*;
import static pooledit.Definitions.*;
import treemodel.XMLTreeNode;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.SpinnerNumberModel;
import org.w3c.dom.Element;

/**
 *
 * @author  jkalmari
 */
public class TableWizard extends javax.swing.JPanel {
    
    private TableGenerator tableGenerator;
    
    private DefaultComboBoxModel fontModel;  
    private DefaultComboBoxModel lineModel;  
    private DefaultComboBoxModel fillModel1;  
    private DefaultComboBoxModel fillModel2;  
    
    /** Creates new form TableWizard */
    public TableWizard() {
        //initComponents();
    }
    
    public void setTableGenerator(TableGenerator tableGenerator) {
        this.tableGenerator = tableGenerator;
        Element root = tableGenerator.getRoot().getModel().getDocument().getDocumentElement();
        fontModel = new DefaultComboBoxModel(WizardTools.findElements(root, FONTATTRIBUTES));
        lineModel = new DefaultComboBoxModel(WizardTools.findElements(root, LINEATTRIBUTES));
        fillModel1 = new DefaultComboBoxModel(WizardTools.findElementsWithEmpty(root, FILLATTRIBUTES));
        fillModel2 = new DefaultComboBoxModel(WizardTools.findElementsWithEmpty(root, FILLATTRIBUTES));
        initComponents();
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        jHeadingRowCheckBox = new javax.swing.JCheckBox();
        jHeightSpinner = new javax.swing.JSpinner();
        jHeadingColCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jWidthSpinner = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCellWidthSpinner = new javax.swing.JSpinner();
        jCellHeightSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCellsHorizontalSpinner = new javax.swing.JSpinner();
        jCellsVerticalSpinner = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFontAttributeComboBox = new javax.swing.JComboBox();
        jLineAttributeComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jHorizontalJustificationComboBox = new javax.swing.JComboBox();
        jVerticalJustificationComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFillAttribute1ComboBox = new javax.swing.JComboBox();
        jFillAttribute2ComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jOffsetSpinner = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jScaleTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jNroDecimalsSpinner = new javax.swing.JSpinner();

        jLabel2.setText("Heading Row Height");

        jHeadingRowCheckBox.setSelected(true);
        jHeadingRowCheckBox.setText("Heading Row");
        jHeadingRowCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jHeadingRowCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jHeightSpinner.setValue(12);
        jHeightSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jHeightSpinnerStateChanged(evt);
            }
        });

        jHeadingColCheckBox.setSelected(true);
        jHeadingColCheckBox.setText("Heading Column");
        jHeadingColCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jHeadingColCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel4.setText("Heading Column Width");

        jWidthSpinner.setValue(32);
        jWidthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jWidthSpinnerStateChanged(evt);
            }
        });

        jLabel5.setText("Column Width");

        jLabel6.setText("Row Height");

        jCellWidthSpinner.setValue(10);
        jCellWidthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCellWidthSpinnerStateChanged(evt);
            }
        });

        jCellHeightSpinner.setValue(10);
        jCellHeightSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCellHeightSpinnerStateChanged(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Columns");

        jLabel8.setText("Rows");

        jCellsHorizontalSpinner.setValue(5);
        jCellsHorizontalSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCellsHorizontalSpinnerStateChanged(evt);
            }
        });

        jCellsVerticalSpinner.setValue(5);
        jCellsVerticalSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCellsVerticalSpinnerStateChanged(evt);
            }
        });

        jLabel9.setText("Font attribute");

        jLabel10.setText("Line attribute");

        jFontAttributeComboBox.setModel(fontModel      );

        jLineAttributeComboBox.setModel(lineModel);

        jLabel12.setText("Horizontal justifiation");

        jLabel13.setText("Vertical justification");

        jHorizontalJustificationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Left", "Middle", "Right" }));
        jHorizontalJustificationComboBox.setSelectedItem("Middle");

        jVerticalJustificationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Top", "Middle", "Bottom" }));
        jVerticalJustificationComboBox.setSelectedItem("Middle");

        jLabel11.setText("Fill attribute (cells)");

        jLabel14.setText("Fill attribute (headings)");

        jFillAttribute1ComboBox.setModel(fillModel1);

        jFillAttribute2ComboBox.setModel(fillModel2);

        jLabel15.setText("Scale");

        jOffsetSpinner.setValue(0);
        jOffsetSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jOffsetSpinnerStateChanged(evt);
            }
        });

        jLabel16.setText("Offset");

        jScaleTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jScaleTextField.setText("1.0");
        jScaleTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jScaleTextFieldFocusLost(evt);
            }
        });

        jLabel17.setText("Number of Decimals");

        jNroDecimalsSpinner.setValue(0);
        jNroDecimalsSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jNroDecimalsSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScaleTextField)
                            .addComponent(jNroDecimalsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel16)
                        .addGap(23, 23, 23)
                        .addComponent(jOffsetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jVerticalJustificationComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFillAttribute2ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFillAttribute1ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFontAttributeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE)
                                .addComponent(jLineAttributeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jHorizontalJustificationComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCellHeightSpinner)
                            .addComponent(jHeightSpinner)
                            .addComponent(jWidthSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jCellWidthSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHeadingRowCheckBox)
                            .addComponent(jHeadingColCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCellsVerticalSpinner)
                                    .addComponent(jCellsHorizontalSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHeadingRowCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jHeightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHeadingColCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCellWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jCellsVerticalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCellHeightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jCellsHorizontalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jOffsetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jNroDecimalsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFontAttributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFillAttribute1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jFillAttribute2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLineAttributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jHorizontalJustificationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVerticalJustificationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jNroDecimalsSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jNroDecimalsSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jNroDecimalsSpinnerStateChanged

    private void jScaleTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScaleTextFieldFocusLost
        String text = jScaleTextField.getText();        
        double value = 1.0;
        try {
            value = Double.valueOf(text);
        } catch (NumberFormatException ex) {
            value = 1.0f;
        }
        jScaleTextField.setText(Double.toString(value));
    }//GEN-LAST:event_jScaleTextFieldFocusLost

    private void jOffsetSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jOffsetSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jOffsetSpinnerStateChanged

    private void jCellsVerticalSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCellsVerticalSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCellsVerticalSpinnerStateChanged

    private void jCellsHorizontalSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCellsHorizontalSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCellsHorizontalSpinnerStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Refresh
        if (tableGenerator != null) {
            tableGenerator.update(); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // OK
        if (tableGenerator != null) {
            tableGenerator.update();
        }
        ((JFrame) this.getParent().getParent().getParent().getParent()).setVisible(false);    //FIXME is this best way to close the window?        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCellHeightSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCellHeightSpinnerStateChanged
        checkSpinnerLimits(jCellHeightSpinner, 0, 65535);
    }//GEN-LAST:event_jCellHeightSpinnerStateChanged

    private void jCellWidthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCellWidthSpinnerStateChanged
        checkSpinnerLimits(jCellWidthSpinner, 0, 65535);
    }//GEN-LAST:event_jCellWidthSpinnerStateChanged

    private void jWidthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jWidthSpinnerStateChanged
        checkSpinnerLimits(jWidthSpinner, 0, 65535);
    }//GEN-LAST:event_jWidthSpinnerStateChanged

    private void jHeightSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jHeightSpinnerStateChanged
        checkSpinnerLimits(jHeightSpinner, 0, 65535);
    }//GEN-LAST:event_jHeightSpinnerStateChanged
    
    public boolean hasHeadingRow(){
        return jHeadingRowCheckBox.getModel().isSelected();
    }
    public boolean hasHeadingColumn(){
        return jHeadingColCheckBox.getModel().isSelected();
    }
    public int getHeadingColumnWidth() {
        return (Integer) ((SpinnerNumberModel) jWidthSpinner.getModel()).getValue();
    }
    public int getHeadingRowHeight() {
        return (Integer) ((SpinnerNumberModel) jHeightSpinner.getModel()).getValue();
    }
    public int getCellWidth() {
        return (Integer) ((SpinnerNumberModel) jCellWidthSpinner.getModel()).getValue();
    }
    public int getCellHeight() {
        return (Integer) ((SpinnerNumberModel) jCellHeightSpinner.getModel()).getValue();
    } 
    public int getCellsHorizontal() {
        return (Integer) ((SpinnerNumberModel) jCellsHorizontalSpinner.getModel()).getValue();
    }
    public int getCellsVertical() {
        return (Integer) ((SpinnerNumberModel) jCellsVerticalSpinner.getModel()).getValue();
    } 
    public String getFontAttribute(){
        return (String) jFontAttributeComboBox.getModel().getSelectedItem();
    }
    public String getLineAttribute(){
        return (String) jLineAttributeComboBox.getModel().getSelectedItem();
    }
    public String getFillAttributeCell(){
        return (String) jFillAttribute1ComboBox.getModel().getSelectedItem();
    }
    public String getFillAttributeHeading(){
        return (String) jFillAttribute2ComboBox.getModel().getSelectedItem();
    }
    public String getHorizontalJustification(){
        return (String) jHorizontalJustificationComboBox.getModel().getSelectedItem();
    }
    public String getVerticalJustification(){
        return (String) jVerticalJustificationComboBox.getModel().getSelectedItem();
    }    
    public int getOffset(){
       return (Integer) ((SpinnerNumberModel) jOffsetSpinner.getModel()).getValue(); 
    }
    public Double getScale() {
        return  Double.valueOf(jScaleTextField.getText());
    }
    public int getNumberOfDecimals() {
         return (Integer) ((SpinnerNumberModel) jNroDecimalsSpinner.getModel()).getValue();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JSpinner jCellHeightSpinner;
    private javax.swing.JSpinner jCellWidthSpinner;
    private javax.swing.JSpinner jCellsHorizontalSpinner;
    private javax.swing.JSpinner jCellsVerticalSpinner;
    private javax.swing.JComboBox jFillAttribute1ComboBox;
    private javax.swing.JComboBox jFillAttribute2ComboBox;
    private javax.swing.JComboBox jFontAttributeComboBox;
    private javax.swing.JCheckBox jHeadingColCheckBox;
    private javax.swing.JCheckBox jHeadingRowCheckBox;
    private javax.swing.JSpinner jHeightSpinner;
    private javax.swing.JComboBox jHorizontalJustificationComboBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jLineAttributeComboBox;
    private javax.swing.JSpinner jNroDecimalsSpinner;
    private javax.swing.JSpinner jOffsetSpinner;
    private javax.swing.JTextField jScaleTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox jVerticalJustificationComboBox;
    private javax.swing.JSpinner jWidthSpinner;
    // End of variables declaration//GEN-END:variables
    
}
