/*
 * Copyright (C) 2019 Automation technology laboratory,
 * Helsinki University of Technology
 *
 * Visit automation.tkk.fi for information about the automation
 * technology laboratory.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston,
 * MA 02111-1307, USA.
 */
package wizard;

import static wizard.WizardTools.*;
import static pooledit.Definitions.*;
import attributetable.AttributeTable;
import color.ColorPalette;
import javax.swing.JFrame;
import javax.swing.ListCellRenderer;
import javax.swing.DefaultComboBoxModel;
import org.w3c.dom.Element;
import treemodel.XMLTreeNode;

/**
 *
 * @author  mohman
 */
public class TrendWizard extends javax.swing.JPanel {
    
    private TrendGenerator trendGenerator;
    
    private final String[] colors = ColorPalette.getAllColorNames();
    private DefaultComboBoxModel<String> colorModel = new DefaultComboBoxModel<>(colors);
    private ListCellRenderer colorRenderer = AttributeTable.createColorListRenderer();
    private DefaultComboBoxModel<String> fillModel1; 
    private DefaultComboBoxModel<String> lineModel1;    
    private DefaultComboBoxModel<String> fillModel2; 
    private DefaultComboBoxModel<String> lineModel2;
    
    private DefaultComboBoxModel<String> fontModel;  

    
    /** Creates new form BeanForm */
    public TrendWizard() {
        // initComponents();
    }
    
    public void setTrendGenerator(TrendGenerator trendGenerator) {
        this.trendGenerator = trendGenerator;
        Element root = trendGenerator.getRoot().getModel().getDocument().getDocumentElement();
        fillModel1 = new DefaultComboBoxModel<>(WizardTools.findElementsWithEmpty(root, FILLATTRIBUTES));
        lineModel1 = new DefaultComboBoxModel<>(WizardTools.findElements(root, LINEATTRIBUTES));
        fillModel2 = new DefaultComboBoxModel<>(WizardTools.findElementsWithEmpty(root, FILLATTRIBUTES));
        lineModel2 = new DefaultComboBoxModel<>(WizardTools.findElements(root, LINEATTRIBUTES));
        
        fontModel = new DefaultComboBoxModel<>(WizardTools.findElements(root, FONTATTRIBUTES));
        initComponents();                
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jWidthSpinner = new javax.swing.JSpinner();
        jHeightSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMinValueSpinner = new javax.swing.JSpinner();
        jMaxValueSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jNroTicksSpinner = new javax.swing.JSpinner();
        jDrawTicksCB = new javax.swing.JCheckBox();
        jHorizontalCB = new javax.swing.JCheckBox();
        jGrowsLeftDownCB = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBarColorCB = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jFillAttribute2CB = new javax.swing.JComboBox();
        jNroBarsSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLineAttribute2CB = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jFillAttribute1CB = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLineAttribute1CB = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTitleTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jFontAttribCB = new javax.swing.JComboBox();
        jShowTitleCB = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jNumbersSpinner = new javax.swing.JSpinner();
        jDrawNumbersCB = new javax.swing.JCheckBox();
        jRefreshButton = new javax.swing.JButton();
        jOKButton = new javax.swing.JButton();
        jDrawBorderCB = new javax.swing.JCheckBox();

        jLabel1.setText("Width");

        jLabel2.setText("Height");

        jWidthSpinner.setValue(100);
        jWidthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jWidthSpinnerStateChanged(evt);
            }
        });

        jHeightSpinner.setValue(100);
        jHeightSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jHeightSpinnerStateChanged(evt);
            }
        });

        jLabel3.setText("Min Value");

        jLabel4.setText("Max Value");

        jMinValueSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMinValueSpinnerStateChanged(evt);
            }
        });

        jMaxValueSpinner.setValue(100);
        jMaxValueSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMaxValueSpinnerStateChanged(evt);
            }
        });

        jLabel5.setText("Nro Ticks");

        jNroTicksSpinner.setValue(11);
        jNroTicksSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jNroTicksSpinnerStateChanged(evt);
            }
        });

        jDrawTicksCB.setSelected(true);
        jDrawTicksCB.setText("Draw Ticks");
        jDrawTicksCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jDrawTicksCB.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jHorizontalCB.setText("Horizontal");
        jHorizontalCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jHorizontalCB.setEnabled(false);
        jHorizontalCB.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jGrowsLeftDownCB.setText("Grows Left / Down");
        jGrowsLeftDownCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jGrowsLeftDownCB.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel6.setText("Nro Bars");

        jLabel7.setText("Bar Color");

        jBarColorCB.setModel(colorModel);
        jBarColorCB.setRenderer(colorRenderer);

        jLabel8.setText("Fill Attribute");

        jFillAttribute2CB.setModel(fillModel2);

        jNroBarsSpinner.setValue(6);
        jNroBarsSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jNroBarsSpinnerStateChanged(evt);
            }
        });

        jLabel9.setText("Line Attribute");

        jLineAttribute2CB.setModel(lineModel2);

        jLabel10.setText("Fill Attribute");

        jFillAttribute1CB.setModel(fillModel1);

        jLabel11.setText("Line Attribute");

        jLineAttribute1CB.setModel(lineModel1);

        jLabel12.setText("Title");

        jTitleTF.setText("trend");

        jLabel13.setText("Font Attribute");

        jFontAttribCB.setModel(fontModel);

        jShowTitleCB.setSelected(true);
        jShowTitleCB.setText("Show Title");
        jShowTitleCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jShowTitleCB.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel14.setText("Numbers");

        jNumbersSpinner.setValue(6);
        jNumbersSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jNumbersSpinnerStateChanged(evt);
            }
        });

        jDrawNumbersCB.setSelected(true);
        jDrawNumbersCB.setText("Draw Numbers");
        jDrawNumbersCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jDrawNumbersCB.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRefreshButton.setText("Refresh");
        jRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshButtonActionPerformed(evt);
            }
        });

        jOKButton.setText("OK");
        jOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed(evt);
            }
        });

        jDrawBorderCB.setText("Draw Border");
        jDrawBorderCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jDrawBorderCB.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jHeightSpinner)
                            .addComponent(jWidthSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGrowsLeftDownCB)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFillAttribute1CB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 99, Short.MAX_VALUE)
                                    .addComponent(jLineAttribute1CB, 0, 99, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel14))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumbersSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jNroTicksSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jMaxValueSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jMinValueSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jNroBarsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDrawNumbersCB)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDrawTicksCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jDrawBorderCB))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBarColorCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 99, Short.MAX_VALUE)
                                    .addComponent(jFillAttribute2CB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 99, Short.MAX_VALUE)
                                    .addComponent(jLineAttribute2CB, 0, 99, Short.MAX_VALUE)))))
                    .addComponent(jHorizontalCB)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jShowTitleCB)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFontAttribCB, 0, 96, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jOKButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRefreshButton)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jWidthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFillAttribute1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jHeightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLineAttribute1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHorizontalCB)
                    .addComponent(jGrowsLeftDownCB))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jNroBarsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jBarColorCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jMinValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jFillAttribute2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jMaxValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLineAttribute2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jNroTicksSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDrawTicksCB)
                        .addComponent(jDrawBorderCB))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jNumbersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDrawNumbersCB))
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jFontAttribCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jShowTitleCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOKButton)
                    .addComponent(jRefreshButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jHeightSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jHeightSpinnerStateChanged
        checkSpinnerLimits(jHeightSpinner, 0, 65535);
    }//GEN-LAST:event_jHeightSpinnerStateChanged

    private void jWidthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jWidthSpinnerStateChanged
        checkSpinnerLimits(jWidthSpinner, 0, 65535);
    }//GEN-LAST:event_jWidthSpinnerStateChanged

    private void jNumbersSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jNumbersSpinnerStateChanged
        checkSpinnerLimits(jNumbersSpinner, 0, 99); // 10 might be too little
    }//GEN-LAST:event_jNumbersSpinnerStateChanged

    private void jNroTicksSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jNroTicksSpinnerStateChanged
        checkSpinnerLimits(jNroTicksSpinner, 0, 99);
    }//GEN-LAST:event_jNroTicksSpinnerStateChanged

    private void jMaxValueSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMaxValueSpinnerStateChanged
        checkSpinnerLimits(jMaxValueSpinner, 0, 65535);
    }//GEN-LAST:event_jMaxValueSpinnerStateChanged

    private void jMinValueSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMinValueSpinnerStateChanged
        checkSpinnerLimits(jMinValueSpinner, 0, 65535);
    }//GEN-LAST:event_jMinValueSpinnerStateChanged

    private void jNroBarsSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jNroBarsSpinnerStateChanged
        checkSpinnerLimits(jNroBarsSpinner, 0, 99);
    }//GEN-LAST:event_jNroBarsSpinnerStateChanged

    private void jRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshButtonActionPerformed
        if (trendGenerator != null) {
            trendGenerator.update(); 
        }
    }//GEN-LAST:event_jRefreshButtonActionPerformed

    private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKButtonActionPerformed
        if (trendGenerator != null) {
            trendGenerator.update();
        }
        ((JFrame) this.getParent().getParent().getParent().getParent()).setVisible(false); 
    }//GEN-LAST:event_jOKButtonActionPerformed
        
    public String getBarColor() {
        return (String) jBarColorCB.getSelectedItem();
    }
    public boolean isDrawBorder() {
        return jDrawBorderCB.isSelected();
    }
    public boolean isDrawNumbers() {
        return jDrawNumbersCB.isSelected();
    }
    public boolean isDrawTicks() {
        return jDrawTicksCB.isSelected();
    }
    public String getFillAttribute1() {
        return (String) jFillAttribute1CB.getSelectedItem();        
    }
    public String getFillAttribute2() {
        return (String) jFillAttribute2CB.getSelectedItem();
    }
    public String getFontAttribute() {
        return (String) jFontAttribCB.getSelectedItem();
    }
    public boolean isGrowsLeftDown() {
        return jGrowsLeftDownCB.isSelected();
    }
    public int getContainerHeight() {
        return (Integer) jHeightSpinner.getValue();
    }
    public boolean isHorizontal() {
        return jHorizontalCB.isSelected();
    }
    public String getLineAttribute1() {
        return (String) jLineAttribute1CB.getSelectedItem();
    }
    public String getLineAttribute2() {
        return (String) jLineAttribute2CB.getSelectedItem();
    }
    public int getMaxValue() {
        return (Integer) jMaxValueSpinner.getValue();
    }    
    public int getMinValue() {
        return (Integer) jMinValueSpinner.getValue();
    }
    public int getNroBars() {
        return (Integer) jNroBarsSpinner.getValue();
    }    
    public int getNroTicks() {
        return (Integer) jNroTicksSpinner.getValue();
    }
    public int getNumbers() {
        return (Integer) jNumbersSpinner.getValue();
    }
    public boolean isDrawTitle() {
        return jShowTitleCB.isSelected();
    }
    public String getTitle() {
        return jTitleTF.getText();
    }
    public int getContainerWidth() {
        return (Integer) jWidthSpinner.getValue();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jBarColorCB;
    private javax.swing.JCheckBox jDrawBorderCB;
    private javax.swing.JCheckBox jDrawNumbersCB;
    private javax.swing.JCheckBox jDrawTicksCB;
    private javax.swing.JComboBox jFillAttribute1CB;
    private javax.swing.JComboBox jFillAttribute2CB;
    private javax.swing.JComboBox jFontAttribCB;
    private javax.swing.JCheckBox jGrowsLeftDownCB;
    private javax.swing.JSpinner jHeightSpinner;
    private javax.swing.JCheckBox jHorizontalCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jLineAttribute1CB;
    private javax.swing.JComboBox jLineAttribute2CB;
    private javax.swing.JSpinner jMaxValueSpinner;
    private javax.swing.JSpinner jMinValueSpinner;
    private javax.swing.JSpinner jNroBarsSpinner;
    private javax.swing.JSpinner jNroTicksSpinner;
    private javax.swing.JSpinner jNumbersSpinner;
    private javax.swing.JButton jOKButton;
    private javax.swing.JButton jRefreshButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jShowTitleCB;
    private javax.swing.JTextField jTitleTF;
    private javax.swing.JSpinner jWidthSpinner;
    // End of variables declaration//GEN-END:variables

}
